import { Metadata } from "next";
import { Inter } from "next/font/google";

import Navigation from "@/components/Navigation.component";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <div className="mx-4">{children}</div>
      </body>
    </html>
  );
}
